version: '3'
services:
  wordpress:
    depends_on: 
      - mysql
    image: wordpress:latest
    restart: always
    volumes: 
      - "./wp-content:/var/www/html/wp-content"
    environment: 
      WORDPRESS_DB_HOST: mysql:${DB_PORT}
      WORDPRESS_DB_PASSWORD: ${AUTH}
    ports:
      - 8000:80
      - 443:443
    networks: 
      - back

  mysql:
    image: mysql:${DB_VER}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTH}
    volumes:
      - wp-data:${DB_DIR}
    networks:
      - back

  phpmyadmin:
    depends_on: 
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment: 
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${AUTH}
    networks:
      - back


networks:
  back:

volumes:
  wp-data: