version: '3'
services:
  wp:
    depends_on: 
      - mysql
    restart: always
    volumes: 
      - ./wp-content:/home/mjohnson/www/wp-sandbox/wp-content
    environment: 
      WORDPRESS_DB_HOST: ${DBHOST}
      WORDPRESS_DB_PASSWORD: ${AUTH}
    build:
        context: .
        dockerfile: docker/Dockerfile
    ports:
      - 80:80
      - 443:443
    networks: 
      - back
  mysql:
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTH}
    volumes:
      - "wp-data:/var/lib/mysql"
    networks:
      - back
  phpmyadmin:
    depends_on: 
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment: 
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${AUTH}
    networks:
      - back
networks:
  back:
volumes:
  wp-data: